### PR TITLE
:lock: Add null checks on every function and system calls

### PR DESCRIPTION
**Pull request by gsegt**
I feel like I over did this one a bit XD

### CODE REVIEW

**Comment by kaoliiny** [comment]
What a heck is going on this MR?!

**Review by kaoliiny — CHANGES_REQUESTED** [review]
Be kind to cancel the MR and never show it to anyone.

**Comment by ickule** [comment]
I had another go at it with assert and a MACRO.
I thought that having a function would be a bit cleaner, even with the macro.
Let me know what you think.

**Review by kaoliiny — CHANGES_REQUESTED** [review]
decline

**Comment by ickule** [comment]
Can you tell me why?
I really don't get what is wrong with this second implementation.

**Comment by kaoliiny** [comment]
This is an outdated comment l made a concilium to actually get the point way this solution is actually right. Can be merged

**Comment by ickule** [comment]
This PR has been rebased on main, I'll let you have another look since quite a bit changed since the solution you approved was made.

**Review by kaoliiny — APPROVED** [review]

**Pull request merged**
